### PR TITLE
fix: revise formatting for docs.yml file

### LINKED ISSUE #47: <bug>: Issue Templates don't appear
## Problem
I noticed that when I click on the "New Issue" button, the templates don't appear. This can caused contributors to be confused. 

## Proposed Solution
According to [the little note in the Configuring Template Chooser section of GitHub's Docs](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#configuring-the-template-chooser), the issue templates will work by by adding a `config.yml` file to the `.github/ISSUE_TEMPLATE` folder and setting `blank_issues_enabled` to `false`. 
**Update**: I realized that some of the syntax in the issue templates were not correct, so I'm going to redo them an see.

## Additional Information
I would like to work on this issue @YuriDevAT.  
```[tasklist]
### Tasks
- [ ] https://github.com/YurisCodingClub/accessibility-mentor/issues/50
- [ ] https://github.com/YurisCodingClub/accessibility-mentor/issues/51
- [ ] https://github.com/YurisCodingClub/accessibility-mentor/issues/52
```

### LINKED ISSUE #51: [BUG] issue template DOCS does not appear
### Description
When raising an issue, the template for [DOCS] does not appear, even though the `docs.yml` file is in the code base.

### Error message
Error message

### Mentioned Link in this message

https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/common-validation-errors-when-creating-issue-forms

The bug and other template appear as expected.

Issue template appearance

```[tasklist]
### Tasks
- [ ] Update the content of the `docs.yml` file
- [ ] if uncertain, compare with the two yml files which are working (`bug.yml`, `other.yml`)
```

### PR DESCRIPTION
**Pull request by CBID2**
_For an example of how to fill this template out, [see this Pull Request in the Wiki](https://github.com/YurisCodingClub/DevCV/wiki/How-to-create-a-pull-request)._

## Description
This PR fixes the formatting in the `docs.yml` file in the Issue template folder. 

## Fixes Issue
Closes #47 
Closes #51 

## Acceptance Criteria
N/A

## Type of Changes
This PR makes the following changes:

- Renames the description field to details to make it more clear what the field is for.
- Adds a label attribute to the details field to make it more readable.
- Updates the description attribute for the details field to provide more specific instructions for what to include in the issue description.
- Renames the possible-solution-and-benefit field to solution to make it more clear what the field is for.
- Updates the description attribute for the solution field to provide more specific instructions for what to include in the proposed solution.
- Adds a validations section to the solution field to make it clear that the proposed solution is required.

Make sure your code follows the code style of this project.
Make sure your code is up2date.
The title of the PR is the same as the title of the issue.

|     | Type                       |
| --- | -------------------------- |
|  x   | :bug: Bug fix              |
|     | :sparkles: New feature     |
|     | :hammer: Refactoring       |
|     | :100: Add tests            |
|     | :link: Update dependencies |
|     | :scroll: Docs              |

### CODE REVIEW

**Comment by YuriDevAT** [comment]
I updated the coressponding issue. Is there a way to check beforehand that the yml file is now working? Can you share these testing steps?

**Comment by CBID2** [comment]
> I updated the corresponding issue. Is there a way to check beforehand that the yml file is now working? Can you share these testing steps?

That's a good question @YuriDevAT. I think the way to test is to see something like this:

**Comment by YuriDevAT** [comment]
I guess this is after merging it? Or can you already see that on your created branch in the forked version?

**Comment by CBID2** [comment]
> I guess this is after merging it? Or can you already see that on your created branch in the forked version?

Let me check

**Comment by YuriDevAT** [comment]
Please resolve conflicts to get this PR merged.

**Comment by CBID2** [comment]
> Please resolve conflicts to get this PR merged.

Well do

**Comment by CBID2** [comment]
Hi @YuriDevAT. The merge conflicts are too difficult to solve, so I'm going to do a new PR for this

**Pull request closed without merging**
