### PR TITLE
bug: revise feature.yml issue template

### LINKED ISSUE #47: <bug>: Issue Templates don't appear
## Problem
I noticed that when I click on the "New Issue" button, the templates don't appear. This can caused contributors to be confused. 

## Proposed Solution
According to [the little note in the Configuring Template Chooser section of GitHub's Docs](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#configuring-the-template-chooser), the issue templates will work by by adding a `config.yml` file to the `.github/ISSUE_TEMPLATE` folder and setting `blank_issues_enabled` to `false`. 
**Update**: I realized that some of the syntax in the issue templates were not correct, so I'm going to redo them an see.

## Additional Information
I would like to work on this issue @YuriDevAT.  
```[tasklist]
### Tasks
- [ ] https://github.com/YurisCodingClub/accessibility-mentor/issues/50
- [ ] https://github.com/YurisCodingClub/accessibility-mentor/issues/51
- [ ] https://github.com/YurisCodingClub/accessibility-mentor/issues/52
```

### LINKED ISSUE #52: [BUG] FEATURE issue template  does not appear
When raising an issue, the template for [FEATURE] does not appear, even though the `feature.yml` file is in the code base.

### Error message
Error message for feature.yml

### Links mentioned in the message
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/common-validation-errors-when-creating-issue-forms#input-is-not-a-permitted-key
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/common-validation-errors-when-creating-issue-forms#bodyi-required-attribute-key-value-is-missing
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/common-validation-errors-when-creating-issue-forms#bodyi-x-is-not-a-permitted-key

### Expected output
The `bug.yml` and `other.yml` template appear as expected.

Issue template appearance

```[tasklist]
### Tasks
- [ ] Update the content of the `feature.yml` file 
- [ ] if uncertain, compare with the two yml files which are working (`bug.yml`, `other.yml`)
```

### PR DESCRIPTION
**Pull request by CBID2**
_For an example of how to fill this template out, [see this Pull Request in the Wiki](https://github.com/YurisCodingClub/DevCV/wiki/How-to-create-a-pull-request)._

## Description

This PR does the following:
- Renames the description input field to feature-description to make it more clear what the input field is for.
- Adds a label attribute to the description input field to make it more readable.
- Updates the description attribute for the description input field to provide more specific instructions for what to include in the feature description.
- Adds validations section to the screenshots input field to make it clear that the screenshots are not required.
## Fixes Issue
Closes #52
Closes #47 

## Acceptance Criteria
N/A

## Type of Changes

Make sure your code follows the code style of this project.
Make sure your code is up2date.
The title of the PR is the same as the title of the issue.

|     | Type                       |
| --- | -------------------------- |
|   X  | :bug: Bug fix              |
|     | :sparkles: New feature     |
|     | :hammer: Refactoring       |
|     | :100: Add tests            |
|     | :link: Update dependencies |
|     | :scroll: Docs              |

### CODE REVIEW

**Comment by YuriDevAT** [comment]
The bug issue template appears. This PR will be closed.

**Comment by YuriDevAT** [comment]
I updated the corresponding issue.

**Comment by YuriDevAT** [comment]
Please resolve conflicts to get this PR merged.

**Comment by CBID2** [comment]
Hi @YuriDevAT. The merge conflicts are too difficult to solve, so I'm going to do a new PR for this

**Pull request closed without merging**
